### ISSUE TITLE
Issues building in Jammy

### ISSUE THREAD

**Issue by liamcarlos** [tesseract-robotics/tesseract_ros2#86]
Hi so I've been attempting to build in Jammy and have been running into some problems, one of which I could not solve.  The package tesseract_qt gives me this error when it searches for graphviz dependencies even though graphviz was installed with apt:

```
CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Graphviz (missing: graphviz_cdt_FOUND graphviz_cgraph_FOUND
  graphviz_gvc_FOUND graphviz_gvpr_FOUND graphviz_lab_gamut_FOUND
  graphviz_pathplan_FOUND graphviz_xdot_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGraphviz.cmake:50 (find_package_handle_standard_args)
  common/CMakeLists.txt:4 (find_package)
```

Besides that there are some small changes in CMakeLists.txt files that could be solved with these commands that might be useful for the build section in readme to make building easier:

```
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./tesseract/tesseract_urdf/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./tesseract/tesseract_environment/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./tesseract/tesseract_visualization/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./trajopt/trajopt/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./trajopt/trajopt_ifopt/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./trajopt/trajopt_optimizers/trajopt_sqp/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./tesseract_planning/tesseract_motion_planners/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./tesseract_planning/tesseract_task_composer/CMakeLists.txt
sed -i -e s/"LANGUAGES CXX"/"LANGUAGES C CXX"/g ./src/tesseract_ros2/tesseract_monitoring/CMakeLists.txt
```

**Comment by rjoomen** [comment]
I'm on Jammy and do not have the Graphviz issue. Do you also have `libgraphviz-dev` installed?

And why exactly should `C` be added to the languages in the CMakeLists?

**Comment by liamcarlos** [comment]
> Do you also have libgraphviz-dev installed?

This fixed it, but now I'm having an issue with ruckig even though I already have it installed with pip..

> And why exactly should C be added to the languages in the CMakeLists?

Because this error pops up for each of those packages:

```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/vtk-9.1/VTK-targets.cmake:518 (set_target_properties):
  The link interface of target "VTK::mpi" contains:

    MPI::MPI_C

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

```

**Comment by lesthaeghet** [comment]
I believe the MPI issue is related to this:  https://gitlab.kitware.com/vtk/vtk/-/issues/17734

Basically, their instructions are that you either explicitly include the C language in your CMake file even if you're only using CXX, or you need to explicitly only include specific VTK components required.  I don't believe the latter generally applies here since VTK is being imported from further under the hood.  So, adding C may be the simplest option.  I've noticed other ROS projects having similar issues and making similar commits recently as well.  I think there was an unrelated bug that was patched in VTK version 9 that caused this to start cropping up in Jammy.  But, there is definitely some inconsistency because we have observed in some Jammy-based environments we can build without modification and in some we need the C language fix.  We're trying to figure out what's causing the difference.

**Comment by rjoomen** [comment]
We went for adding C to the languages where required. If another solution is found, please let is know.
